/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import CONTROLADOR.FileHandler;
import CONTROLADOR.Validaciones;
import MODELO.Carga;
import MODELO.CargaRegular;
import MODELO.MaterialPeligroso;
import MODELO.MercanciaPerecedera;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author keilagarcia
 */
public class AgregarCargas extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCargas
     */
    private static Main interfazMain;
    private FileHandler fichero;
    private LinkedList<Carga> cargasList;

    public AgregarCargas(Main main) {
        initComponents();

        interfazMain = main;
        fichero = new FileHandler();
        cargasList = new LinkedList<>();

        try {
            cargarCargas(fichero.mostrarCargas());
        } catch (IOException ex) {
            System.out.println("No se encuentra el archivo");
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar el archivo");
        }

        OcultarPanel();
    }

    public void cargarCargas(LinkedList<Carga> cargas) {
        for (Carga carga : cargas) {
            cargasList.add(carga);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtFabricante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtIdentificador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpnValor = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jTxtPaisProcedencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jBtnInicio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSpnIndiceRiesgo = new javax.swing.JSpinner();
        jTxtFechaCaducidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCbTipoCarga = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtTipoMercancia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCbNacional = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTxtTipoRiesgo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCbTransporte = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSpnHoraEntrega = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("AGREGAR CARGAS");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("FABRICANTE");

        jLabel4.setText("IDENTIFICADOR");

        jLabel5.setText("MARCA");

        jLabel6.setText("VALOR");

        jSpnValor.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jLabel7.setText("PAIS PROCEDENCIA");

        jLabel8.setText("FECHA CADUCIDAD");

        jBtnAgregar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jBtnAgregar.setText("AGREGAR");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnInicio.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jBtnInicio.setText("INICIO");
        jBtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInicioActionPerformed(evt);
            }
        });

        jLabel9.setText("INDICE DE RIESGO");

        jSpnIndiceRiesgo.setModel(new javax.swing.SpinnerNumberModel(0.01d, 0.01d, 1.0d, 0.01d));

        jLabel10.setText("TIPO CARGA");

        jCbTipoCarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "MERCANCIA PERECEDERA", "MATERIAL PELIGROSO", "CARGA REGULAR" }));
        jCbTipoCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTipoCargaActionPerformed(evt);
            }
        });

        jLabel11.setText("TIPO DE MERCANCIA");

        jLabel12.setText("MERCANCIA");

        jCbNacional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NACIONAL", "IMPORTADA" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtTipoMercancia)
                    .addComponent(jCbNacional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTxtTipoMercancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCbNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("TIPO RIESGO");

        jLabel14.setText("TRANSPORTADO POR");

        jCbTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AIRE", "TIERRA" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtTipoRiesgo)
                    .addComponent(jCbTransporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtTipoRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jCbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("HORARIO ENTREGA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(41, 41, 41)
                .addComponent(jSpnHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jSpnHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jBtnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnInicio)
                        .addGap(166, 166, 166))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtNombre)
                                    .addComponent(jTxtFabricante)
                                    .addComponent(jTxtIdentificador)
                                    .addComponent(jTxtMarca)
                                    .addComponent(jTxtPaisProcedencia)
                                    .addComponent(jTxtFechaCaducidad)
                                    .addComponent(jCbTipoCarga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addComponent(jSpnIndiceRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jSpnIndiceRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTxtPaisProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCbTipoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregar)
                    .addComponent(jBtnInicio))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInicioActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setLocationRelativeTo(null);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnInicioActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        Validaciones valida = new Validaciones();

        if (valida.campoVacio(jTxtNombre.getText())) {
            if (valida.campoVacio(jTxtFabricante.getText())) {
                if (valida.sinEspacios(jTxtIdentificador.getText())) {
                    if (valida.campoVacio(jTxtPaisProcedencia.getText())) {
                        if (!jTxtFechaCaducidad.getText().equals("")) {
                            if (jCbTipoCarga.getSelectedIndex() == 1) {
                                if (jCbNacional.getSelectedIndex() == 0) {
                                    MercanciaPerecedera mercaP = new MercanciaPerecedera(jTxtTipoMercancia.getText(), true, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(mercaP);
                                    try {
                                        fichero.guardarCarga(mercaP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                } else {
                                    MercanciaPerecedera mercaP = new MercanciaPerecedera(jTxtTipoMercancia.getText(), false, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(mercaP);
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardarCarga(mercaP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                }
                            } else if (jCbTipoCarga.getSelectedIndex() == 2) {
                                if (jCbTransporte.getSelectedIndex() == 0) {
                                    MaterialPeligroso materialP = new MaterialPeligroso(jTxtTipoRiesgo.getText(), true, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(materialP);
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardarCarga(materialP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                } else {
                                    MaterialPeligroso materialP = new MaterialPeligroso(jTxtTipoRiesgo.getText(), false, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(materialP);
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardarCarga(materialP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                }
                            } else if (jCbTipoCarga.getSelectedIndex() == 3) {
                                CargaRegular cargaT = new CargaRegular(Integer.valueOf(jSpnHoraEntrega.getValue().toString()), jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                cargasList.add(cargaT);
                                try {
                                    fichero.guardar(cargasList);
                                } catch (IOException ex) {
                                    Logger.getLogger(AgregarCargas.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                try {
                                    fichero.guardarCarga(cargaT);
                                } catch (IOException ex) {
                                    Logger.getLogger(AgregarCargas.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                
                                mostrarMensaje("Guardado con exito");
                                limpiarCampos();
                            }
                        } else {
                            if (jCbTipoCarga.getSelectedIndex() == 1) {
                                if (jCbNacional.getSelectedIndex() == 0) {
                                    MercanciaPerecedera mercaP = new MercanciaPerecedera(jTxtTipoMercancia.getText(), true, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(mercaP);
                                    try {
                                        fichero.guardarCarga(mercaP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                } else {
                                    MercanciaPerecedera mercaP = new MercanciaPerecedera(jTxtTipoMercancia.getText(), false, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), jTxtFechaCaducidad.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(mercaP);
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardarCarga(mercaP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                }
                            } else if (jCbTipoCarga.getSelectedIndex() == 2) {
                                if (jCbTransporte.getSelectedIndex() == 0) {
                                    MaterialPeligroso materialP = new MaterialPeligroso(jTxtTipoRiesgo.getText(), true, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(materialP);
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardarCarga(materialP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                } else {
                                    MaterialPeligroso materialP = new MaterialPeligroso(jTxtTipoRiesgo.getText(), false, jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                    cargasList.add(materialP);
                                    try {
                                        fichero.guardar(cargasList);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    try {
                                        fichero.guardarCarga(materialP);
                                    } catch (IOException ex) {
                                        mostrarMensaje("Error " + ex);
                                    }
                                    
                                    mostrarMensaje("Guardado con exito");
                                    limpiarCampos();
                                }
                            } else if (jCbTipoCarga.getSelectedIndex() == 3) {
                                CargaRegular cargaT = new CargaRegular(Integer.valueOf(jSpnHoraEntrega.getValue().toString()), jTxtNombre.getText(), jTxtFabricante.getText(), jTxtIdentificador.getText(), jTxtMarca.getText(), jTxtPaisProcedencia.getText(), Double.valueOf(jSpnValor.getValue().toString()), Double.valueOf(jSpnIndiceRiesgo.getValue().toString()));
                                cargasList.add(cargaT);
                                try {
                                    fichero.guardar(cargasList);
                                } catch (IOException ex) {
                                    Logger.getLogger(AgregarCargas.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                try {
                                    fichero.guardarCarga(cargaT);
                                } catch (IOException ex) {
                                    Logger.getLogger(AgregarCargas.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                
                                mostrarMensaje("Guardado con exito");
                                limpiarCampos();
                            }
                        }
                    } else {
                        mostrarMensaje("Agregar Pais Procedencia");
                    }
                } else {
                    mostrarMensaje("El identificador no debe contener espacios o estar vacio");
                }
            } else {
                mostrarMensaje("Agregar Fabricante");
            }
        } else {
            mostrarMensaje("Agregar nombre");
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jCbTipoCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTipoCargaActionPerformed
        // TODO add your handling code here:
        if (jCbTipoCarga.getSelectedIndex() == 1) {
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
        } else if (jCbTipoCarga.getSelectedIndex() == 2) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
        } else if (jCbTipoCarga.getSelectedIndex() == 3) {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(true);
        } else {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
        }
    }//GEN-LAST:event_jCbTipoCargaActionPerformed

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(rootPane, mensaje);
    }

    public void limpiarCampos() {
        jTxtNombre.setText("");
        jTxtFabricante.setText("");
        jTxtIdentificador.setText("");
        jTxtMarca.setText("");
        jTxtPaisProcedencia.setText("");
        jTxtFechaCaducidad.setText("");
        jTxtTipoRiesgo.setText("");
        jTxtTipoMercancia.setText("");
        jCbTipoCarga.setSelectedIndex(0);
    }

    public void OcultarPanel() {
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AgregarCargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnInicio;
    private javax.swing.JComboBox<String> jCbNacional;
    private javax.swing.JComboBox<String> jCbTipoCarga;
    private javax.swing.JComboBox<String> jCbTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpnHoraEntrega;
    private javax.swing.JSpinner jSpnIndiceRiesgo;
    private javax.swing.JSpinner jSpnValor;
    private javax.swing.JTextField jTxtFabricante;
    private javax.swing.JTextField jTxtFechaCaducidad;
    private javax.swing.JTextField jTxtIdentificador;
    private javax.swing.JTextField jTxtMarca;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtPaisProcedencia;
    private javax.swing.JTextField jTxtTipoMercancia;
    private javax.swing.JTextField jTxtTipoRiesgo;
    // End of variables declaration//GEN-END:variables
}
